spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:hsqldb:mem:testdb
#    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
    password:
    hikari:
      pool-name: NCube JDBC Connection Pool
      maximum-pool-size: 50

ncube:
  allow:
    mutable:
      methods: false